### ISSUE TITLE
snakemake error - FileNotFoundError: [Errno 2] No such file or directory: EXPR.csv

### ISSUE THREAD

**Issue by pillailab** [LiuzLab/SalmonTE#32]
Hello,
I am getting the following error which running the quant function
SalmonTE.py quant --reference=hs --outpath=~/scratch60/SF3B1/SRP061203/SRX1098126/ --num_threads=8 $fq1 $fq2

I tried changing snakemake version to 5.1.5 but error repeats. I am running using a conda environment, not sure if that it is relevant.
thanks !
Manoj

2019-05-17 07:01:02,225 Starting quantification mode
2019-05-17 07:01:02,227 Collecting FASTQ files...
2019-05-17 07:01:02,417 The input dataset is considered as a paired-ends dataset.
2019-05-17 07:01:02,418 Collected 1 FASTQ files.
2019-05-17 07:01:02,418 Quantification has been finished.
2019-05-17 07:01:02,418 Running Salmon using Snakemake
NameError in line 24 of /ysm-gpfs/home/mp758/project/Tools/SalmonTE/SalmonTE/snakemake/Snakefile.paired:
name 'directory' is not defined
  File "/ysm-gpfs/home/mp758/project/Tools/SalmonTE/SalmonTE/snakemake/Snakefile.paired", line 24, in <module>
2019-05-17 07:01:04,603 NameError in line 24 of /ysm-gpfs/home/mp758/project/Tools/SalmonTE/SalmonTE/snakemake/Snakefile.paired:
name 'directory' is not defined
  File "/ysm-gpfs/home/mp758/project/Tools/SalmonTE/SalmonTE/snakemake/Snakefile.paired", line 24, in <module>
Traceback (most recent call last):
  File "/ysm-gpfs/home/mp758/project/Tools/SalmonTE/SalmonTE/SalmonTE.py", line 289, in <module>
    run(args)
  File "/ysm-gpfs/home/mp758/project/Tools/SalmonTE/SalmonTE/SalmonTE.py", line 240, in run
    run_salmon(param)
  File "/ysm-gpfs/home/mp758/project/Tools/SalmonTE/SalmonTE/SalmonTE.py", line 156, in run_salmon
    with open(os.path.join(param["--outpath"], "EXPR.csv" ), "r") as inp:
FileNotFoundError: [Errno 2] No such file or directory: '~/scratch60/SF3B1/SRP061203/SRX1098126/EXPR.csv'

**Comment by hyunhwaj** [comment]
Hello @pillailab,

It seems that the error is similar to #27. What does $fq1 and $fq2 contains?

Hyun-Hwan Jeong

**Comment by pillailab** [comment]
Hi Hyun-Hwan,
Thanks - i did try different versions of snake make (the latest version was erroring out without starting snakemake and installed 5.2).
fq1 and fq2 are aliases for fastq files
fq1=/home/mp758/scratch60/SF3B1/SRP061203/SRX1098126/fastq/SRX1098126_1.fastq.gz
fq2=/home/mp758/scratch60/SF3B1/SRP061203/SRX1098126/fastq/SRX1098126_2.fastq.gz
Manoj

**Comment by hyunhwaj** [comment]
@pillailab 

Can you try `--outpath=/home/mp758/scratch60/SF3B1/SRP061203/SRX1098126/` instead of  `--outpath=~/scratch60/SF3B1/SRP061203/SRX1098126/`?

Thank you,

Hyun-Hwan Jeong

**Comment by pillailab** [comment]
@hyunhwaj ,
That seems to have fixed it and i got the output files. Thank you !
Manoj

**Comment by hyunhwaj** [comment]
@pillailab, good to hear that! I will try to find the solution for how SalmonTE can handle your initial command line.

Kind Regards,

Hyun-Hwan Jeong
