### ISSUE TITLE
SyntaxError on test data running SalmonTE

### ISSUE THREAD

**Issue by Xiaofei-git** [LiuzLab/SalmonTE#55]
Dear there,

I tried to install SalmonTE. But, I failed to make it run on test data and did't figure out why did it happen. 

Really appreciate for any help!

Best,

Xiaofei

```
$ SalmonTE.py quant --reference=hs example/CTRL_1_R1.fastq example/CTRL_2_R1.fastq
2021-07-08 14:00:37,748 Starting quantification mode
2021-07-08 14:00:37,748 Collecting FASTQ files...
2021-07-08 14:00:37,753 The input dataset is considered as a single-end dataset.
2021-07-08 14:00:37,754 Collected 2 FASTQ files.
2021-07-08 14:00:37,754 Quantification has been finished.
2021-07-08 14:00:37,754 Running Salmon using Snakemake
Traceback (most recent call last):
  File "/Users/xwang/Desktop/software/SalmonTE/SalmonTE.py", line 292, in <module>
    run(args)
  File "/Users/xwang/Desktop/software/SalmonTE/SalmonTE.py", line 243, in run
    run_salmon(param)
  File "/Users/xwang/Desktop/software/SalmonTE/SalmonTE.py", line 140, in run_salmon
    import snakemake
  File "/Users/xwang/anaconda3/lib/python3.8/site-packages/snakemake/__init__.py", line 20, in <module>
    from snakemake.workflow import Workflow
  File "/Users/xwang/anaconda3/lib/python3.8/site-packages/snakemake/workflow.py", line 23, in <module>
    from snakemake.shell import shell
  File "/Users/xwang/anaconda3/lib/python3.8/site-packages/snakemake/shell.py", line 69
    async=False,
    ^
SyntaxError: invalid syntax
```

**Comment by Xiaofei-git** [comment]
In fact, it is paired-end. I do't know why it is considered as single-end "2021-07-08 14:00:37,753 The input dataset is considered as a single-end dataset".

**Comment by hyunhwan-jeong** [comment]
Hi @Xiaofei-git, the first thing I could figure out is that the file name has to be `example/CTRL_1_R1.fastq example/CTRL_1_R2.fastq` instead of `example/CTRL_1_R1.fastq example/CTRL_2_R1.fastq`. `CTRL_1_R1.fastq` and `CTRL_2_R1.fastq` are from different samples, so SalmonTE would not consider them as paired-end samples.

Regarding another error, I may need to have more inputs from you. Could you inform me what you see either `pip list` or `conda list`?

Thank you,

Hyun-Hwan Jeong

**Comment by Xiaofei-git** [comment]
> Hi @Xiaofei-git, the first thing I could figure out is that the file name has to be `example/CTRL_1_R1.fastq example/CTRL_1_R2.fastq` instead of `example/CTRL_1_R1.fastq example/CTRL_2_R1.fastq`. `CTRL_1_R1.fastq` and `CTRL_2_R1.fastq` are from different samples, so SalmonTE would not consider them as paired-end samples.
> 
> Regarding another error, I may need to have more inputs from you. Could you inform me what you see either `pip list` or `conda list`?
> 
> Thank you,
> 
> Hyun-Hwan Jeong

Yes, you are right. I did't realize I used different samples of R1.

For another error, here are the what I see from "pip list" and "conda list":

```
$ pip list
Package                            Version
---------------------------------- -----------------
alabaster                          0.7.12
amply                              0.1.4
anaconda-client                    1.7.2
anaconda-navigator                 1.10.0
anaconda-project                   0.8.3
appdirs                            1.4.4
applaunchservices                  0.2.1
appnope                            0.1.0
appscript                          1.1.1
argh                               0.26.2
argon2-cffi                        20.1.0
asn1crypto                         1.4.0
astroid                            2.4.2
astropy                            4.0.2
async-generator                    1.10
atomicwrites                       1.4.0
attrs                              21.2.0
autopep8                           1.5.4
Babel                              2.8.1
backcall                           0.2.0
backports.functools-lru-cache      1.6.1
backports.shutil-get-terminal-size 1.0.0
backports.tempfile                 1.0
backports.weakref                  1.0.post1
beautifulsoup4                     4.9.3
biopython                          1.78
bitarray                           1.6.1
bkcharts                           0.2
bleach                             3.2.1
bokeh                              2.2.3
boto                               2.49.0
boto3                              1.17.106
botocore                           1.20.106
Bottleneck                         1.3.2
brotlipy                           0.7.0
bs4                                0.0.1
certifi                            2021.5.30
cffi                               1.14.3
chardet                            4.0.0
click                              7.1.2
cloudpickle                        1.6.0
clyent                             1.2.2
colorama                           0.4.4
conda                              4.10.1
conda-build                        3.20.5
conda-package-handling             1.7.2
conda-verify                       3.4.2
ConfigArgParse                     1.5.1
connection-pool                    0.0.3
contextlib2                        0.6.0.post1
cryptography                       3.1.1
cycler                             0.10.0
Cython                             0.29.21
cytoolz                            0.11.0
dask                               2.30.0
datrie                             0.8.2
decorator                          4.4.2
defusedxml                         0.6.0
diff-match-patch                   20200713
distributed                        2.30.1
docopt                             0.6.2
docutils                           0.17.1
entrypoints                        0.3
et-xmlfile                         1.0.1
fastcache                          1.1.0
filelock                           3.0.12
flake8                             3.8.4
Flask                              1.1.2
fsspec                             0.8.3
future                             0.18.2
gevent                             20.9.0
gitdb                              4.0.7
GitPython                          3.1.18
glob2                              0.7
gmpy2                              2.0.8
greenlet                           0.4.17
gseapy                             0.9.5
h5py                               2.10.0
HeapDict                           1.0.1
html5lib                           1.1
idna                               2.10
imageio                            2.9.0
imagesize                          1.2.0
importlib-metadata                 2.0.0
iniconfig                          1.1.1
intervaltree                       3.1.0
ipykernel                          5.3.4
ipython                            7.19.0
ipython-genutils                   0.2.0
ipywidgets                         7.5.1
isort                              5.6.4
itsdangerous                       1.1.0
jdcal                              1.4.1
jedi                               0.17.1
Jinja2                             3.0.1
jmespath                           0.10.0
joblib                             0.17.0
json5                              0.9.5
jsonschema                         3.2.0
jupyter                            1.0.0
jupyter-client                     6.1.7
jupyter-console                    6.2.0
jupyter-core                       4.6.3
jupyterlab                         2.2.6
jupyterlab-pygments                0.1.2
jupyterlab-server                  1.2.0
keyring                            21.4.0
kiwisolver                         1.3.0
lazy-object-proxy                  1.4.3
libarchive-c                       2.9
llvmlite                           0.34.0
locket                             0.2.0
lxml                               4.6.1
MarkupSafe                         2.0.1
matplotlib                         3.3.2
mccabe                             0.6.1
mistune                            0.8.4
mkl-fft                            1.2.0
mkl-random                         1.1.1
mkl-service                        2.3.0
mock                               4.0.2
more-itertools                     8.6.0
mpmath                             1.1.0
msgpack                            1.0.0
multipledispatch                   0.6.0
navigator-updater                  0.2.1
nbclient                           0.5.1
nbconvert                          6.0.7
nbformat                           5.0.8
nest-asyncio                       1.4.2
networkx                           2.5.1
nltk                               3.5
nose                               1.3.7
notebook                           6.1.4
numba                              0.51.2
numexpr                            2.7.1
numpy                              1.19.2
numpydoc                           1.1.0
olefile                            0.46
openpyxl                           3.0.5
packaging                          20.4
pandas                             1.1.3
pandocfilters                      1.4.3
parso                              0.7.0
partd                              1.1.0
path                               15.0.0
pathlib2                           2.3.5
pathtools                          0.1.2
patsy                              0.5.1
pep8                               1.7.1
pexpect                            4.8.0
pickleshare                        0.7.5
Pillow                             8.0.1
pip                                20.2.4
pkginfo                            1.6.1
pluggy                             0.13.1
ply                                3.11
prometheus-client                  0.8.0
prompt-toolkit                     3.0.8
psutil                             5.7.2
ptyprocess                         0.6.0
PuLP                               2.4
py                                 1.9.0
pycodestyle                        2.6.0
pycosat                            0.6.3
pycparser                          2.20
pycurl                             7.43.0.6
pydocstyle                         5.1.1
pyflakes                           2.2.0
Pygments                           2.7.2
pylint                             2.6.0
pyodbc                             4.0.0-unsupported
pyOpenSSL                          19.1.0
pyparsing                          2.4.7
pyrsistent                         0.18.0
PySocks                            1.7.1
pytest                             0.0.0
python-dateutil                    2.8.1
python-jsonrpc-server              0.4.0
python-language-server             0.35.1
pytz                               2020.1
PyWavelets                         1.1.1
PyYAML                             5.4.1
pyzmq                              19.0.2
QDarkStyle                         2.8.1
QtAwesome                          1.0.1
qtconsole                          4.7.7
QtPy                               1.9.0
ratelimiter                        1.2.0.post0
regex                              2020.10.15
requests                           2.25.1
rope                               0.18.0
Rtree                              0.9.4
ruamel-yaml                        0.15.87
s3transfer                         0.4.2
scikit-image                       0.17.2
scikit-learn                       0.23.2
scipy                              1.5.2
seaborn                            0.11.0
Send2Trash                         1.5.0
setuptools                         57.1.0
simplegeneric                      0.8.1
singledispatch                     3.4.0.3
six                                1.16.0
smart-open                         5.1.0
smmap                              4.0.0
snakemake                          5.1.5
snowballstemmer                    2.0.0
sortedcollections                  1.2.1
sortedcontainers                   2.2.2
soupsieve                          2.0.1
Sphinx                             3.2.1
sphinxcontrib-applehelp            1.0.2
sphinxcontrib-devhelp              1.0.2
sphinxcontrib-htmlhelp             1.0.3
sphinxcontrib-jsmath               1.0.1
sphinxcontrib-qthelp               1.0.3
sphinxcontrib-serializinghtml      1.1.4
sphinxcontrib-websupport           1.2.4
spyder                             4.1.5
spyder-kernels                     1.9.4
SQLAlchemy                         1.3.20
statsmodels                        0.12.0
stopit                             1.1.2
sympy                              1.6.2
tables                             3.6.1
tabulate                           0.8.9
tblib                              1.7.0
terminado                          0.9.1
testpath                           0.4.4
threadpoolctl                      2.1.0
tifffile                           2020.10.1
toml                               0.10.1
toolz                              0.11.1
toposort                           1.6
tornado                            6.0.4
tqdm                               4.50.2
traitlets                          5.0.5
typing-extensions                  3.7.4.3
ujson                              4.0.1
unicodecsv                         0.14.1
urllib3                            1.26.6
watchdog                           0.10.3
wcwidth                            0.2.5
webencodings                       0.5.1
Werkzeug                           1.0.1
wheel                              0.35.1
widgetsnbextension                 3.5.1
wrapt                              1.12.1
wurlitzer                          2.0.1
xlrd                               1.2.0
XlsxWriter                         1.3.7
xlwings                            0.20.8
xlwt                               1.3.0
xmltodict                          0.12.0
yapf                               0.30.0
zict                               2.0.0
zipp                               3.4.0
zope.event                         4.5.0
zope.interface                     5.1.2
```

```
$ conda list
# packages in environment at /Users/xwang/anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0                    py38_0  
alabaster                 0.7.12                     py_0  
anaconda                  2020.11                  py38_0  
anaconda-client           1.7.2                    py38_0  
anaconda-navigator        1.10.0                   py38_0  
anaconda-project          0.8.4                      py_0  
appdirs                   1.4.4                    pypi_0    pypi
applaunchservices         0.2.1                      py_0  
appnope                   0.1.0                 py38_1001  
appscript                 1.1.1            py38haf1e3a3_0  
argh                      0.26.2                   py38_0  
argon2-cffi               20.1.0           py38haf1e3a3_1  
asn1crypto                1.4.0                      py_0  
astroid                   2.4.2                    py38_0  
astropy                   4.0.2            py38haf1e3a3_0  
async_generator           1.10                       py_0  
atomicwrites              1.4.0                      py_0  
attrs                     21.2.0                   pypi_0    pypi
autopep8                  1.5.4                      py_0  
babel                     2.8.1              pyhd3eb1b0_0  
backcall                  0.2.0                      py_0  
backports                 1.0                        py_2  
backports.functools_lru_cache 1.6.1                      py_0  
backports.shutil_get_terminal_size 1.0.0                    py38_2  
backports.tempfile        1.0                        py_1  
backports.weakref         1.0.post1                  py_1  
beautifulsoup4            4.9.3              pyhb0f4dca_0  
bedtools                  2.30.0               h6eb76b4_0    bioconda
bioawk                    1.0                  h2573ce8_5    bioconda
biopython                 1.78             py38h96a0964_2    conda-forge
bitarray                  1.6.1            py38h9ed2024_0  
bkcharts                  0.2                      py38_0  
blas                      1.0                         mkl  
bleach                    3.2.1                      py_0  
blosc                     1.20.1               hab81aa3_0  
bokeh                     2.2.3                    py38_0  
boto                      2.49.0                   py38_0  
boto3                     1.17.106                 pypi_0    pypi
botocore                  1.20.106                 pypi_0    pypi
bottleneck                1.3.2            py38hf1fa96c_1  
brotlipy                  0.7.0           py38haf1e3a3_1000  
bs4                       0.0.1                    pypi_0    pypi
bzip2                     1.0.8                h1de35cc_0  
ca-certificates           2020.10.14                    0  
certifi                   2021.5.30                pypi_0    pypi
cffi                      1.14.3           py38hed5b41f_0  
chardet                   4.0.0                    pypi_0    pypi
click                     7.1.2                      py_0  
cloudpickle               1.6.0                      py_0  
clyent                    1.2.2                    py38_1  
colorama                  0.4.4                      py_0  
conda                     4.10.1           py38hecd8cb5_1  
conda-build               3.20.5                   py38_1  
conda-env                 2.6.0                         1  
conda-package-handling    1.7.2            py38h22f3db7_0  
conda-verify              3.4.2                      py_1  
configargparse            1.5.1                    pypi_0    pypi
contextlib2               0.6.0.post1                py_0  
cryptography              3.1.1            py38hddc9c9b_0  
curl                      7.71.1               hb0a8c7a_1  
cycler                    0.10.0                   py38_0  
cython                    0.29.21          py38hb1e8313_0  
cytoolz                   0.11.0           py38haf1e3a3_0  
dask                      2.30.0                     py_0  
dask-core                 2.30.0                     py_0  
datrie                    0.8.2                    pypi_0    pypi
dbus                      1.13.18              h18a8e69_0  
decorator                 4.4.2                      py_0  
defusedxml                0.6.0                      py_0  
diff-match-patch          20200713                   py_0  
distributed               2.30.1           py38hecd8cb5_0  
docutils                  0.17.1                   pypi_0    pypi
entrypoints               0.3                      py38_0  
et_xmlfile                1.0.1                   py_1001  
expat                     2.2.10               hb1e8313_2  
fastcache                 1.1.0            py38h1de35cc_0  
filelock                  3.0.12                     py_0  
flake8                    3.8.4                      py_0  
flask                     1.1.2                      py_0  
freetype                  2.10.4               ha233b18_0  
fsspec                    0.8.3                      py_0  
future                    0.18.2                   py38_1  
get_terminal_size         1.0.0                h7520d66_0  
gettext                   0.19.8.1             hb0f4f8b_2  
gevent                    20.9.0           py38haf1e3a3_0  
glib                      2.66.1               h9bbe63b_0  
glob2                     0.7                        py_0  
gmp                       6.1.2                hb37e062_1  
gmpy2                     2.0.8            py38h6ef4df4_3  
greenlet                  0.4.17           py38haf1e3a3_0  
gseapy                    0.9.5                      py_1    bioconda
h5py                      2.10.0           py38h3134771_0  
hdf5                      1.10.4               hfa1e0ec_0  
heapdict                  1.0.1                      py_0  
html5lib                  1.1                        py_0  
icu                       58.2                 h0a44026_3  
idna                      2.10                       py_0  
imageio                   2.9.0                      py_0  
imagesize                 1.2.0                      py_0  
importlib-metadata        2.0.0                      py_1  
importlib_metadata        2.0.0                         1  
iniconfig                 1.1.1                      py_0  
intel-openmp              2019.4                      233  
intervaltree              3.1.0                      py_0  
ipykernel                 5.3.4            py38h5ca1d4c_0  
ipython                   7.19.0           py38h01d92e1_0  
ipython_genutils          0.2.0                    py38_0  
ipywidgets                7.5.1                      py_1  
isort                     5.6.4                      py_0  
itsdangerous              1.1.0                      py_0  
jbig                      2.1                  h4d881f8_0  
jdcal                     1.4.1                      py_0  
jedi                      0.17.1                   py38_0  
jinja2                    3.0.1                    pypi_0    pypi
jmespath                  0.10.0                   pypi_0    pypi
joblib                    0.17.0                     py_0  
jpeg                      9b                   he5867d9_2  
json5                     0.9.5                      py_0  
jsonschema                3.2.0                      py_2  
jupyter                   1.0.0                    py38_7  
jupyter_client            6.1.7                      py_0  
jupyter_console           6.2.0                      py_0  
jupyter_core              4.6.3                    py38_0  
jupyterlab                2.2.6                      py_0  
jupyterlab_pygments       0.1.2                      py_0  
jupyterlab_server         1.2.0                      py_0  
keyring                   21.4.0                   py38_1  
kiwisolver                1.3.0            py38h23ab428_0  
krb5                      1.18.2               h75d18d8_0  
lazy-object-proxy         1.4.3            py38h1de35cc_0  
lcms2                     2.11                 h92f6f08_0  
libarchive                3.4.2                haa3ed63_0  
libcurl                   7.71.1               h8a08a2b_1  
libcxx                    10.0.0                        1  
libedit                   3.1.20191231         h1de35cc_1  
libffi                    3.3                  hb1e8313_2  
libgcc                    4.8.5               hdbeacc1_10  
libgfortran               3.0.1                h93005f0_2  
libiconv                  1.16                 h1de35cc_0  
liblief                   0.10.1               h0a44026_0  
libllvm10                 10.0.1               h76017ad_5  
libpng                    1.6.37               ha441bb4_0  
libsodium                 1.0.18               h1de35cc_0  
libspatialindex           1.9.3                h0a44026_0  
libssh2                   1.9.0                ha12b0ac_1  
libtiff                   4.1.0                hcb84e12_1  
libxml2                   2.9.10               h7cdb67c_3  
libxslt                   1.1.34               h83b36ba_0  
llvm-openmp               10.0.0               h28b9765_0  
llvmlite                  0.34.0           py38h739e7dc_4  
locket                    0.2.0                    py38_1  
lxml                      4.6.1            py38h63b7cb6_0  
lz4-c                     1.9.2                h79c402e_3  
lzo                       2.10                 haf1e3a3_2  
markupsafe                2.0.1                    pypi_0    pypi
matplotlib                3.3.2                         0  
matplotlib-base           3.3.2            py38h181983e_0  
mccabe                    0.6.1                    py38_1  
mistune                   0.8.4           py38h1de35cc_1001  
mkl                       2019.4                      233  
mkl-service               2.3.0            py38hfbe908c_0  
mkl_fft                   1.2.0            py38hc64f4ea_0  
mkl_random                1.1.1            py38h959d312_0  
mock                      4.0.2                      py_0  
more-itertools            8.6.0              pyhd3eb1b0_0  
mpc                       1.1.0                h6ef4df4_1  
mpfr                      4.0.2                h9066e36_1  
mpmath                    1.1.0                    py38_0  
msgpack-python            1.0.0            py38h04f5b5a_1  
multipledispatch          0.6.0                    py38_0  
navigator-updater         0.2.1                    py38_0  
nbclient                  0.5.1                      py_0  
nbconvert                 6.0.7                    py38_0  
nbformat                  5.0.8                      py_0  
ncurses                   6.2                  h0a44026_1  
nest-asyncio              1.4.2              pyhd3eb1b0_0  
networkx                  2.5.1                    pypi_0    pypi
nltk                      3.5                        py_0  
nose                      1.3.7                 py38_1004  
notebook                  6.1.4                    py38_0  
numba                     0.51.2           py38h6440ff4_1  
numexpr                   2.7.1            py38hce01a72_0  
numpy                     1.19.2           py38h456fd55_0  
numpy-base                1.19.2           py38hcfb5961_0  
numpydoc                  1.1.0              pyhd3eb1b0_1  
olefile                   0.46                       py_0  
openjdk                   11.0.6               h7bc2e8c_1  
openpyxl                  3.0.5                      py_0  
openssl                   1.1.1h               haf1e3a3_0  
packaging                 20.4                       py_0  
pandas                    1.1.3            py38hb1e8313_0  
pandoc                    2.11                 h0dc7051_0  
pandocfilters             1.4.3            py38hecd8cb5_1  
parso                     0.7.0                      py_0  
partd                     1.1.0                      py_0  
path                      15.0.0                   py38_0  
path.py                   12.5.0                        0  
pathlib2                  2.3.5                    py38_1  
pathtools                 0.1.2                      py_1  
patsy                     0.5.1                    py38_0  
pcre                      8.44                 hb1e8313_0  
pep8                      1.7.1                    py38_0  
perl                      5.26.2               h4e221da_0  
perl-bioperl              1.6.924                       4    bioconda/label/cf201901
perl-threaded             5.26.0                        0    bioconda
perl-yaml                 1.29                    pl526_0    bioconda
pexpect                   4.8.0                    py38_1  
pickleshare               0.7.5                 py38_1001  
pillow                    8.0.1            py38h5270095_0  
pip                       20.2.4           py38hecd8cb5_0  
pkginfo                   1.6.1            py38hecd8cb5_0  
pluggy                    0.13.1                   py38_0  
ply                       3.11                     py38_0  
prometheus_client         0.8.0                      py_0  
prompt-toolkit            3.0.8                      py_0  
prompt_toolkit            3.0.8                         0  
psutil                    5.7.2            py38haf1e3a3_0  
ptyprocess                0.6.0                    py38_0  
py                        1.9.0                      py_0  
py-lief                   0.10.1           py38haf313ee_0  
pycodestyle               2.6.0                      py_0  
pycosat                   0.6.3            py38h1de35cc_1  
pycparser                 2.20                       py_2  
pycurl                    7.43.0.6         py38hddc9c9b_0  
pydocstyle                5.1.1                      py_0  
pyflakes                  2.2.0                      py_0  
pygments                  2.7.2              pyhd3eb1b0_0  
pylint                    2.6.0                    py38_0  
pyodbc                    4.0.30           py38h0a44026_0  
pyopenssl                 19.1.0                     py_1  
pyparsing                 2.4.7                      py_0  
pyqt                      5.9.2            py38h655552a_2  
pyrsistent                0.18.0                   pypi_0    pypi
pysocks                   1.7.1                    py38_1  
pytables                  3.6.1            py38h4727e94_0  
pytest                    6.1.1                    py38_0  
python                    3.8.5                h26836e1_1  
python-dateutil           2.8.1                      py_0  
python-jsonrpc-server     0.4.0                      py_0  
python-language-server    0.35.1                     py_0  
python-libarchive-c       2.9                        py_0  
python.app                2                       py38_10  
python_abi                3.8                      1_cp38    conda-forge
pytz                      2020.1                     py_0  
pywavelets                1.1.1            py38haf1e3a3_2  
pyyaml                    5.4.1                    pypi_0    pypi
pyzmq                     19.0.2           py38hb1e8313_1  
qdarkstyle                2.8.1                      py_0  
qt                        5.9.7                h468cd18_1  
qtawesome                 1.0.1                      py_0  
qtconsole                 4.7.7                      py_0  
qtpy                      1.9.0                      py_0  
ratelimiter               1.2.0.post0              pypi_0    pypi
readline                  8.0                  h1de35cc_0  
regex                     2020.10.15       py38haf1e3a3_0  
requests                  2.25.1                   pypi_0    pypi
ripgrep                   12.1.1                        0  
rope                      0.18.0                     py_0  
rtree                     0.9.4                    py38_1  
ruamel_yaml               0.15.87          py38haf1e3a3_1  
s3transfer                0.4.2                    pypi_0    pypi
scikit-image              0.17.2           py38h81aa140_0  
scikit-learn              0.23.2           py38h959d312_0  
scipy                     1.5.2            py38h2515648_0  
seaborn                   0.11.0                     py_0  
send2trash                1.5.0                    py38_0  
setuptools                57.1.0                   pypi_0    pypi
simplegeneric             0.8.1                    py38_2  
singledispatch            3.4.0.3                 py_1001  
sip                       4.19.8           py38h0a44026_0  
six                       1.16.0                   pypi_0    pypi
snakemake                 5.1.5                    pypi_0    pypi
snowballstemmer           2.0.0                      py_0  
snpeff                    5.0                           0    bioconda
snpsift                   4.3.1t                        2    bioconda
sortedcollections         1.2.1                      py_0  
sortedcontainers          2.2.2                      py_0  
soupsieve                 2.0.1                      py_0  
sphinx                    3.2.1                      py_0  
sphinxcontrib             1.0                      py38_1  
sphinxcontrib-applehelp   1.0.2                      py_0  
sphinxcontrib-devhelp     1.0.2                      py_0  
sphinxcontrib-htmlhelp    1.0.3                      py_0  
sphinxcontrib-jsmath      1.0.1                      py_0  
sphinxcontrib-qthelp      1.0.3                      py_0  
sphinxcontrib-serializinghtml 1.1.4                      py_0  
sphinxcontrib-websupport  1.2.4                      py_0  
spyder                    4.1.5                    py38_0  
spyder-kernels            1.9.4                    py38_0  
sqlalchemy                1.3.20           py38h9ed2024_0  
sqlite                    3.33.0               hffcf06c_0  
statsmodels               0.12.0           py38haf1e3a3_0  
sympy                     1.6.2            py38hecd8cb5_1  
tblib                     1.7.0                      py_0  
terminado                 0.9.1                    py38_0  
testpath                  0.4.4                      py_0  
threadpoolctl             2.1.0              pyh5ca1d4c_0  
tifffile                  2020.10.1        py38h0cf3a3e_2  
tk                        8.6.10               hb0a8c7a_0  
toml                      0.10.1                     py_0  
toolz                     0.11.1                     py_0  
tornado                   6.0.4            py38h1de35cc_1  
tqdm                      4.50.2                     py_0  
traitlets                 5.0.5                      py_0  
typing_extensions         3.7.4.3                    py_0  
ujson                     4.0.1            py38hb1e8313_0  
unicodecsv                0.14.1                   py38_0  
unixodbc                  2.3.9                haf1e3a3_0  
urllib3                   1.26.6                   pypi_0    pypi
watchdog                  0.10.3           py38haf1e3a3_0  
wcwidth                   0.2.5                      py_0  
webencodings              0.5.1                    py38_1  
werkzeug                  1.0.1                      py_0  
wheel                     0.35.1                     py_0  
widgetsnbextension        3.5.1                    py38_0  
wrapt                     1.12.1                   pypi_0    pypi
wurlitzer                 2.0.1                    py38_0  
xlrd                      1.2.0                      py_0  
xlsxwriter                1.3.7                      py_0  
xlwings                   0.20.8                   py38_0  
xlwt                      1.3.0                    py38_0  
xmltodict                 0.12.0                     py_0  
xz                        5.2.5                h1de35cc_0  
yaml                      0.2.5                haf1e3a3_0  
yapf                      0.30.0                     py_0  
zeromq                    4.3.3                hb1e8313_3  
zict                      2.0.0                      py_0  
zipp                      3.4.0              pyhd3eb1b0_0  
zlib                      1.2.11               h1de35cc_3  
zope                      1.0                      py38_1  
zope.event                4.5.0                    py38_0  
zope.interface            5.1.2            py38haf1e3a3_0  
zstd                      1.4.5                h41d2c2f_0
```

**Comment by Xiaofei-git** [comment]
Dear @hyunhwan-jeong ,

I am checking back to see do you have any idea about the error?

Thanks a lot!

BEST,

Xiaofei

**Comment by hyunhwan-jeong** [comment]
Hi @Xiaofei-git,

I guess the snakemake version has a compatibility issue with SalmonTE. I believe it could be solved if you install the latest version of snakemake. You can install the latest version with the following command - `pip install snakemake --upgrade`

Hyun-Hwan Jeong

**Comment by Xiaofei-git** [comment]
@hyunhwan-jeong

The error was fixed with latest version of snakelike. 

$ snakemake -v
6.6.1

But, got another error as below

```
$ SalmonTE.py quant --reference=hs example
2021-07-20 07:45:00,108 Starting quantification mode
2021-07-20 07:45:00,108 Collecting FASTQ files...
2021-07-20 07:45:00,108 SalmonTE assumes that 'example' is a directory, and SalmonTE will search any FASTQ file in the directory.
2021-07-20 07:45:00,115 The input dataset is considered as a paired-ends dataset.
2021-07-20 07:45:00,115 Collected 4 FASTQ files.
2021-07-20 07:45:00,115 Quantification has been finished.
2021-07-20 07:45:00,115 Running Salmon using Snakemake
2021-07-20 07:45:00,366 Lock 4378001808 acquired on /var/folders/43/wqcsdbhd3vs8wpxp0903j0g40000gp/T/tmpd0rnswwisnakemake-runtime-source-cache/aacb3f05655970a320900b0dd13afa984b937a586ed442e59223e95ebfacd6b6.lock
2021-07-20 07:45:00,367 Lock 4378001808 released on /var/folders/43/wqcsdbhd3vs8wpxp0903j0g40000gp/T/tmpd0rnswwisnakemake-runtime-source-cache/aacb3f05655970a320900b0dd13afa984b937a586ed442e59223e95ebfacd6b6.lock
/Users/xwang/Desktop/software/SalmonTE/snakemake/Snakefile.paired:103: SyntaxWarning: "is" with a literal. Did you mean "=="?
Job stats:
job                    count    min threads    max threads
-------------------  -------  -------------  -------------
all                        1              1              1
collect_abundance          1              1              1
collect_mappability        1              1              1
run_salmon_fq              4              1              1
total                      7              1              1

2021-07-20 07:45:00,454 Job stats:
job                    count    min threads    max threads
-------------------  -------  -------------  -------------
all                        1              1              1
collect_abundance          1              1              1
collect_mappability        1              1              1
run_salmon_fq              4              1              1
total                      7              1              1

/bin/bash: line 1: 35133 Abort trap: 6           /Users/xwang/Desktop/software/SalmonTE/salmon/darwin/bin/salmon quant -q -i /Users/xwang/Desktop/software/SalmonTE/reference/hs -l A -1 /var/folders/43/wqcsdbhd3vs8wpxp0903j0g40000gp/T/tmp_lp_l6lr/TARDBP_1_R1.fastq -2 /var/folders/43/wqcsdbhd3vs8wpxp0903j0g40000gp/T/tmp_lp_l6lr/TARDBP_1_R2.fastq -o /Users/xwang/Desktop/software/SalmonTE/SalmonTE_output/TARDBP_1 -p 4 2> /dev/null
[Tue Jul 20 07:45:00 2021]
2021-07-20 07:45:00,649 [Tue Jul 20 07:45:00 2021]
Error in rule run_salmon_fq:
2021-07-20 07:45:00,650 Error in rule run_salmon_fq:
    jobid: 5
2021-07-20 07:45:00,650     jobid: 5
    output: /Users/xwang/Desktop/software/SalmonTE/SalmonTE_output/TARDBP_1
2021-07-20 07:45:00,650     output: /Users/xwang/Desktop/software/SalmonTE/SalmonTE_output/TARDBP_1
    shell:
        /Users/xwang/Desktop/software/SalmonTE/salmon/darwin/bin/salmon quant -q -i /Users/xwang/Desktop/software/SalmonTE/reference/hs -l A -1 /var/folders/43/wqcsdbhd3vs8wpxp0903j0g40000gp/T/tmp_lp_l6lr/TARDBP_1_R1.fastq -2 /var/folders/43/wqcsdbhd3vs8wpxp0903j0g40000gp/T/tmp_lp_l6lr/TARDBP_1_R2.fastq -o /Users/xwang/Desktop/software/SalmonTE/SalmonTE_output/TARDBP_1 -p 4 2>/dev/null
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
2021-07-20 07:45:00,650     shell:
        /Users/xwang/Desktop/software/SalmonTE/salmon/darwin/bin/salmon quant -q -i /Users/xwang/Desktop/software/SalmonTE/reference/hs -l A -1 /var/folders/43/wqcsdbhd3vs8wpxp0903j0g40000gp/T/tmp_lp_l6lr/TARDBP_1_R1.fastq -2 /var/folders/43/wqcsdbhd3vs8wpxp0903j0g40000gp/T/tmp_lp_l6lr/TARDBP_1_R2.fastq -o /Users/xwang/Desktop/software/SalmonTE/SalmonTE_output/TARDBP_1 -p 4 2>/dev/null
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

2021-07-20 07:45:00,650 
Exiting because a job execution failed. Look above for error message
2021-07-20 07:45:00,652 Exiting because a job execution failed. Look above for error message
Traceback (most recent call last):
  File "/Users/xwang/Desktop/software/SalmonTE/SalmonTE.py", line 292, in <module>
    run(args)
  File "/Users/xwang/Desktop/software/SalmonTE/SalmonTE.py", line 243, in run
    run_salmon(param)
  File "/Users/xwang/Desktop/software/SalmonTE/SalmonTE.py", line 156, in run_salmon
    with open(os.path.join(param["--outpath"], "EXPR.csv" ), "r") as inp:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/xwang/Desktop/software/SalmonTE/SalmonTE_output/EXPR.csv'
```

**Comment by hyunhwan-jeong** [comment]
@Xiaofei-git are you running this on macOS?

Hyun-Hwan Jeong

**Comment by Xiaofei-git** [comment]
> @Xiaofei-git are you running this on macOS?
> 
> Hyun-Hwan Jeong

Yes.

**Comment by hyunhwan-jeong** [comment]
@Xiaofei-git,

You may execute the line before you run SalmonTE

```
export DYLD_LIBRARY_PATH=/Users/xwang/Desktop/software/SalmonTE/salmon/darwin/lib
```

Or you can add the command to your shell configuration (e.g., `.bashrc`).

Hope it helps,

Hyun-Hwan Jeong

**Comment by Xiaofei-git** [comment]
> @Xiaofei-git,
> 
> You may execute the line before you run SalmonTE
> 
> ```
> export DYLD_LIBRARY_PATH=/Users/xwang/Desktop/software/SalmonTE/salmon/darwin/lib
> ```
> 
> Or you can add the command to your shell configuration (e.g., `.bashrc`).
> 
> Hope it helps,
> 
> Hyun-Hwan Jeong

Thanks a lot!
