### ISSUE TITLE
error: Failed to solve scheduling problem with ILP solver

### ISSUE THREAD

**Issue by Shirleyyyyyy** [LiuzLab/SalmonTE#56]
Hello,I got an error as follow. 
I update snakemake (6.6.1), but it did not work either.

SalmonTE.py quant --num_threads 10 --reference=hs ~/SalmonTE/example/CTRL_1_R1.fastq ~/SalmonTE/example/CTRL_1_R2.fastq 

2021-07-29 19:56:25,823 Starting quantification mode
2021-07-29 19:56:25,823 Collecting FASTQ files...
2021-07-29 19:56:25,830 The input dataset is considered as a paired-ends dataset.
2021-07-29 19:56:25,830 Collected 1 FASTQ files.
2021-07-29 19:56:25,830 Quantification has been finished.
2021-07-29 19:56:25,830 Running Salmon using Snakemake
2021-07-29 19:56:26,513 Lock 140044027502800 acquired on /tmp/tmpk47j2fprsnakemake-runtime-source-cache/a25b8035675db9f47eac5986a70af6136e78a16e4a8d2d9ca00c61e28658f4c1.lock
2021-07-29 19:56:26,514 Lock 140044027502800 released on /tmp/tmpk47j2fprsnakemake-runtime-source-cache/a25b8035675db9f47eac5986a70af6136e78a16e4a8d2d9ca00c61e28658f4c1.lock
Job stats:
job                    count    min threads    max threads
-------------------  -------  -------------  -------------
all                        1              1              1
collect_abundance          1              1              1
collect_mappability        1              1              1
run_salmon_fq              1              1              1
total                      4              1              1

2021-07-29 19:56:26,756 Job stats:
job                    count    min threads    max threads
-------------------  -------  -------------  -------------
all                        1              1              1
collect_abundance          1              1              1
collect_mappability        1              1              1
run_salmon_fq              1              1              1
total                      4              1              1

Failed to solve scheduling problem with ILP solver. Falling back to greedy solver. Run Snakemake with --verbose to see the full solver output for debugging the problem.
Failed to solve scheduling problem with ILP solver. Falling back to greedy solver. Run Snakemake with --verbose to see the full solver output for debugging the problem.

**Comment by hyunhwan-jeong** [comment]
Hi @Shirleyyyyyy,

Did the command generate any output?  I don't think the bottom messages are error messages. I wonder what will happen if you run without `--num_threads` parameter.

Thank you,

Hyun-Hwan Jeong

**Comment by Shirleyyyyyy** [comment]
Hi,@hyunhwan-jeong. Thanks for your reply.

1.This is the output I got. Is this the final result supposed to be?
![image](https://user-images.githubusercontent.com/29476667/127590187-da6a7030-2efd-49e7-9674-900c54c41d3e.png)

2.I tried without --num_threads parameter, and the same error is shown as below.
SalmonTE.py quant --reference=hs ~/SalmonTE/example/CTRL_1_R1.fastq ~/SalmonTE/example/CTRL_1_R2.fastq
2021-07-30 10:20:33,651 Starting quantification mode
2021-07-30 10:20:33,652 Collecting FASTQ files...
2021-07-30 10:20:33,790 The input dataset is considered as a paired-ends dataset.
2021-07-30 10:20:33,790 Collected 1 FASTQ files.
2021-07-30 10:20:33,790 Quantification has been finished.
2021-07-30 10:20:33,791 Running Salmon using Snakemake
2021-07-30 10:20:57,955 Lock 140286377502864 acquired on /tmp/tmpx2tdreumsnakemake-runtime-source-cache/a25b8035675db9f47eac5986a70af6136e78a16e4a8d2d9ca00c61e28658f4c1.lock
2021-07-30 10:20:57,963 Lock 140286377502864 released on /tmp/tmpx2tdreumsnakemake-runtime-source-cache/a25b8035675db9f47eac5986a70af6136e78a16e4a8d2d9ca00c61e28658f4c1.lock
Job stats:
job                    count    min threads    max threads
all                        1              1              1
collect_abundance          1              1              1
collect_mappability        1              1              1
run_salmon_fq              1              1              1
total                      4              1              1

2021-07-30 10:21:01,895 Job stats:
job                    count    min threads    max threads
all                        1              1              1
collect_abundance          1              1              1
collect_mappability        1              1              1
run_salmon_fq              1              1              1
total                      4              1              1

Failed to solve scheduling problem with ILP solver. Falling back to greedy solver. Run Snakemake with --verbose to see the full solver output for debugging the problem.
Failed to solve scheduling problem with ILP solver. Falling back to greedy solver. Run Snakemake with --verbose to see the full solver output for debugging the problem.

3.BUT if I use my own fastq data to run, more errors are shown as follows. Do you have any idea about what appened here?
SalmonTE.py quant --reference=mm ../O4C2-Ctr-1.R1.fastq ../O4C2-Ctr-1.R2.fastq
2021-07-30 10:27:23,831 Starting quantification mode
2021-07-30 10:27:23,831 Collecting FASTQ files...
2021-07-30 10:27:23,926 The input dataset is considered as a paired-ends dataset.
2021-07-30 10:27:23,926 Collected 1 FASTQ files.
2021-07-30 10:27:23,926 Quantification has been finished.
2021-07-30 10:27:23,926 Running Salmon using Snakemake
2021-07-30 10:27:24,603 Lock 140153770384720 acquired on /tmp/tmppcxacfx0snakemake-runtime-source-cache/a25b8035675db9f47eac5986a7
0af6136e78a16e4a8d2d9ca00c61e28658f4c1.lock
2021-07-30 10:27:24,604 Lock 140153770384720 released on /tmp/tmppcxacfx0snakemake-runtime-source-cache/a25b8035675db9f47eac5986a7
0af6136e78a16e4a8d2d9ca00c61e28658f4c1.lock
Job stats:
job                    count    min threads    max threads
all                        1              1              1
collect_abundance          1              1              1
collect_mappability        1              1              1
total                      3              1              1

2021-07-30 10:27:24,843 Job stats:
job                    count    min threads    max threads
all                        1              1              1
collect_abundance          1              1              1
collect_mappability        1              1              1
total                      3              1              1

Failed to solve scheduling problem with ILP solver. Falling back to greedy solver. Run Snakemake with --verbose to see the full so
lver output for debugging the problem.
[Fri Jul 30 10:27:27 2021]
Error in rule collect_mappability:
    jobid: 0
    output: /Share/home/zhangqf3/haojing/chz/RNA-seq/cat/SalmonTE/SalmonTE_output/MAPPING_INFO.csv

RuleException:
KeyError in line 98 of /Share2/home/zhangqf3/SalmonTE/snakemake/Snakefile.paired:
"None of ['SampleID'] are in the columns"
  File "/Share2/home/zhangqf3/SalmonTE/snakemake/Snakefile.paired", line 98, in __rule_collect_mappability
  File "/Share/home/zhangqf3/apps/anaconda2/lib/python3.7/site-packages/pandas/core/frame.py", line 4555, in set_index
  File "/Share/home/zhangqf3/apps/anaconda2/lib/python3.7/concurrent/futures/thread.py", line 57, in run
Exiting because a job execution failed. Look above for error message
Exiting because a job execution failed. Look above for error message
2021-07-30 10:27:28,105 Exiting because a job execution failed. Look above for error message
Traceback (most recent call last):
  File "/Share2/home/zhangqf3/SalmonTE/SalmonTE.py", line 292, in <module>
    run(args)
  File "/Share2/home/zhangqf3/SalmonTE/SalmonTE.py", line 243, in run
    run_salmon(param)
  File "/Share2/home/zhangqf3/SalmonTE/SalmonTE.py", line 156, in run_salmon
    with open(os.path.join(param["--outpath"], "EXPR.csv" ), "r") as inp:
FileNotFoundError: [Errno 2] No such file or directory: '/Share/home/zhangqf3/haojing/chz/RNA-seq/cat/SalmonTE/SalmonTE_output/EXPR.csv'

**Comment by hyunhwan-jeong** [comment]
@Shirleyyyyyy 

1. Yes, the files were expected.
2. Again, this is a warning message and not an error message.
3. Could you change the file name to `O4C2-Ctr-1-R1_fastq`O4C2-Ctr-1_R2.fastq`?

Thank you,

Hyun-Hwan Jeong
